default:
 FINBOT_DB:
  driver: "ODBC Driver 13 for SQL Server"
  server: "T1PRANMSQL\\SQLPROD"
  database: "MA_AM_NS_DATA"
  uid: ""
  pwd: ""
  trusted: "yes"
  
production: 
 FINBOT_DB:
  driver: "ODBC Driver 13 for SQL Server"
  server: "T1PRANMSQL.ad.hq.dept,60125"
  database: "MA_AM_NS_DATA"
  uid: !expr Sys.getenv("FINBOT_UID")
  pwd: !expr Sys.getenv("FINBOT_PWD")
  trusted: "no"
